version: 'latest'
services:
  dev-db:
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: nestjs
    networks:
     - localdev
  test-db:
    image: postgres:latest
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: e2e_postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: nestjs
    networks:
     - localdev
networks:
  localdev: